version: "3.9"

services:
  Postgres:
    image: postgres:alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: myPassword
      POSTGRES_DB: myDB
  RabbitMq:
    image: rabbitmq:3-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
  MongoStorage:
    image: mongo:6-jammy
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always
  TicTacToeServer:
    image: tictactoeserver
    container_name: TicTacToeServer
    ports:
      - "7289:80"
    environment:
      - ConnectionStrings__Postgres=User ID=root;Password=myPassword;Host=postgres;Port=5432;Database=myDB;Pooling=true;Connection Lifetime=0;
      - ConnectionStrings__RabbitMq=amqp://admin:admin@rabbitmq:5672
      - ConnectionStrings__MongoDb=mongodb://mongodb:27017
      - JwtSettings__Issuer=TicTacToeServer
      - JwtSettings__Audience=TicTacToeServer
      - JwtSettings__Key=somEverYsecuReandsecRetkeYforjWt
      - ASPNETCORE_URLS=http://+:80
    build:
      context: ./TicTacToeServer
      dockerfile: Dockerfile
    depends_on:
      - Postgres
      - RabbitMq
      - MongoStorage
  TicTacToeFront:
    image: tictactoefront
    container_name: TicTacToeFront
    ports:
      - "3000:3000"
    build:
      context: ./front
      dockerfile: Dockerfile